import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { databaseBackupApi, backupError, type DatabaseBackupSettings } from '../api/databaseBackupApi';
import { useAuthStore } from '../stores/authStore';
const section = 'rounded-xl border bg-white p-4 space-y-4 min-w-0';
const button = 'px-4 py-3 rounded bg-emerald-800 text-white disabled:opacity-50';
const field = 'block w-full min-w-0 border rounded p-3 mt-1';
const date = (value?: string) => value ? new Date(value).toLocaleString() : 'None';
const time = (hour: number, minute: number) => `${String(hour).padStart(2, '0')}:${String(minute).padStart(2, '0')}`;
const warnings: Record<string, string> = {
  storage_durability_unconfirmed: 'Storage durability is unconfirmed. Automatic backups require persistent storage.',
  offsite_copy_not_configured: 'No offsite copy is configured. Losing this server could lose local backups.',
  external_assets_and_roles_require_separate_recovery: 'Complete recovery also needs separately protected encryption keys, database roles and external application assets.',
  retention_paused_without_verified_offsite: 'Retention is paused until offsite copies are verified. Configure offsite storage or explicitly review the local-only retention policy.',
  postgres_tools_missing: 'PostgreSQL backup tools are missing.', encryption_key_unavailable: 'Backup encryption is not configured.',
  storage_not_configured: 'The deployment administrator must configure protected storage.', low_disk_space: 'Backup storage has insufficient free space.',
};
export default function DatabaseBackupPanel() {
  const user = useAuthStore(s => s.user); const scope = `${user?.id}:${user?.currentBusiness?.businessId}`;
  const cache = useQueryClient(); const queryKey = ['settings', 'database-backup', scope];
  const query = useQuery({ queryKey, queryFn: databaseBackupApi.overview, retry: false, refetchInterval: 15000, enabled: user?.currentBusiness?.role === 'SuperAdmin' });
  const [draft, setDraft] = useState<DatabaseBackupSettings | null>(null), [notice, setNotice] = useState(''), [failure, setFailure] = useState('');
  const [selected, setSelected] = useState(''), [confirmed, setConfirmed] = useState(false);
  const operation = useMutation({ mutationFn: async (action: () => Promise<unknown>) => action(), onSuccess: () => { setNotice(current => current || 'Request completed. Queued jobs continue on the server.'); setFailure(''); void cache.invalidateQueries({ queryKey }); }, onError: error => { setFailure(backupError(error)); void cache.invalidateQueries({ queryKey }); } });
  const save = useMutation({ mutationFn: databaseBackupApi.settings, onSuccess: () => { setDraft(null); setNotice('Server schedules saved.'); setFailure(''); void cache.invalidateQueries({ queryKey }); }, onError: error => setFailure(backupError(error)) });
  function run(action: () => Promise<unknown>) { setNotice(''); setFailure(''); operation.mutate(action); }
  if (user?.currentBusiness?.role !== 'SuperAdmin') return <section className={section}><h2 className="text-lg font-semibold">Database recovery backups</h2><p>Authorized platform operators manage database recovery. Business downloads below are operational exports.</p></section>;
  if (query.isLoading) return <section className={section}><p role="status">Loading database backup settings…</p></section>;
  if (query.isError || !query.data) return <section className={section}><h2 className="text-lg font-semibold">Database recovery backups</h2><p role="alert">{backupError(query.error)}</p><button className={button} onClick={() => void query.refetch()}>Retry database backup settings</button></section>;
  const { overview: data, canRecover } = query.data; const settings = draft ?? data.settings;
  const active = data.jobs.some(j => ['queued', 'running'].includes(j.status)); const busy = operation.isPending || save.isPending;
  const archives = data.jobs.filter(j => j.status === 'succeeded' && j.kind !== 'verify');
  const selectedArchive = archives.find(j => j.id === selected);
  const recoveryVerified = data.jobs.some(j => j.kind === 'verify' && j.status === 'succeeded' && j.sourceId === selected && !!j.completedAt && query.dataUpdatedAt - Date.parse(j.completedAt) <= 3600000);
  const update = (values: Partial<DatabaseBackupSettings>) => setDraft({ ...settings, ...values });
  const number = (label: string, key: 'dailyRetention' | 'monthlyRetention' | 'manualRetention' | 'monthlyDay', max: number) => <label className="block">{label}<input type="number" className={field} min={1} max={max} required value={settings[key]} disabled={busy} onChange={e => update({ [key]: Number(e.target.value) })} /></label>;
  return <section className={section} aria-label="Database recovery backups"><h2 className="text-lg font-semibold">Database recovery backups</h2><p>Encrypted archives cover the full database and every business. Only configured platform operators can access them.</p>
    {notice && <p role="status" className="text-emerald-800">{notice}</p>}{failure && <p role="alert" className="text-red-700">{failure}</p>}
    <div className="rounded border p-3 space-y-2"><p>Destination: {data.health.destination} · Durability: {data.health.durability}</p><p>Server health: {data.health.ready ? 'Ready' : 'Needs attention'} · Last successful backup: {date(data.lastSuccessful)}</p><ul className="list-disc pl-5">{data.health.warnings.map(w => <li key={w}>{warnings[w] ?? `Server health needs attention (${w}).`}</li>)}</ul></div>
    {!data.settings.dailyEnabled && !data.settings.monthlyEnabled && <p role="status">Automatic database backups are disabled.</p>}
    <button className={button} disabled={busy || active || !data.health.ready} onClick={() => run(databaseBackupApi.create)}>Create Backup Now</button>{active && <p role="status">An operation is queued or running. Progress refreshes automatically.</p>}
    <form className="space-y-4" onSubmit={e => { e.preventDefault(); setNotice(''); setFailure(''); save.mutate(settings); }}>
      <label className="block">Schedule time zone<input className={field} value={settings.timeZone} required maxLength={100} disabled={busy} onChange={e => update({ timeZone: e.target.value })} /></label>
      <div className="grid md:grid-cols-2 gap-4"><fieldset className="border rounded p-3 space-y-3"><legend className="px-2 font-semibold">Daily backup</legend><label className="flex items-center gap-3 min-h-12"><input type="checkbox" checked={settings.dailyEnabled} disabled={busy} onChange={e => update({ dailyEnabled: e.target.checked })} />Enable daily server backups</label><label className="block">Daily time<input type="time" className={field} value={time(settings.dailyHour, settings.dailyMinute)} required disabled={busy} onChange={e => { const [dailyHour, dailyMinute] = e.target.value.split(':').map(Number); update({ dailyHour, dailyMinute }); }} /></label><p>Next daily run: {date(data.nextDaily)}</p>{number('Daily backups to keep', 'dailyRetention', 365)}</fieldset>
      <fieldset className="border rounded p-3 space-y-3"><legend className="px-2 font-semibold">Monthly backup</legend><label className="flex items-center gap-3 min-h-12"><input type="checkbox" checked={settings.monthlyEnabled} disabled={busy} onChange={e => update({ monthlyEnabled: e.target.checked })} />Enable monthly server backups</label>{number('Day of month', 'monthlyDay', 31)}<label className="block">Monthly time<input type="time" className={field} value={time(settings.monthlyHour, settings.monthlyMinute)} required disabled={busy} onChange={e => { const [monthlyHour, monthlyMinute] = e.target.value.split(':').map(Number); update({ monthlyHour, monthlyMinute }); }} /></label><p>Short months use their last day. Next monthly run: {date(data.nextMonthly)}</p>{number('Monthly backups to keep', 'monthlyRetention', 120)}</fieldset></div>
      {number('Manual backups to keep', 'manualRetention', 365)}<p className="text-sm">Schedules run independently of the browser while the server is available. After downtime, the current day or month is caught up. Disabling a schedule cancels pending runs; a running backup finishes safely. Pinned archives and the latest validated archive in each category are retained.</p><button className={button} disabled={busy || !draft}>Save backup schedules</button>{draft && <button type="button" className="underline px-4 min-h-12" disabled={busy} onClick={() => { setDraft(null); void query.refetch(); }}>Discard settings changes</button>}
    </form><h3 className="font-semibold">Database backup history</h3><p className="text-sm">Latest 100 jobs. Verification checks archive integrity and schema compatibility. An isolated restore drill is also required.</p>
    {data.jobs.length === 0 ? <p>No database backups yet.</p> : <ol className="space-y-3">{data.jobs.map(job => <li className="border rounded p-3 space-y-2 break-words" key={job.id}><p><strong>{job.status}</strong> · {job.kind} · {date(job.createdAt)}</p><p>{job.stage} · Attempt {job.attempts} · Completed: {date(job.completedAt)}</p>{job.kind !== 'verify' && job.status === 'succeeded' && <p>{job.id.replaceAll('-', '')}.wab</p>}{job.errorCode && <p role="alert">Operation failed ({job.errorCode}). Existing backups were preserved.</p>}{job.sizeBytes != null && <p>{job.sizeBytes.toLocaleString()} bytes · Verified: {date(job.verifiedAt)} · {job.pinned ? 'Protected' : 'Retention applies'}</p>}{data.health.offsiteConfigured && job.status === 'succeeded' && job.kind !== 'verify' && !job.offsiteVerified && <p role="alert">Offsite copy was not verified. Administrator attention is required.</p>}{job.status === 'succeeded' && job.kind !== 'verify' && <div className="flex flex-wrap gap-3"><button className={button} disabled={busy} onClick={() => run(() => databaseBackupApi.download(job.id))}>Download encrypted archive</button><button className={button} disabled={busy || active} onClick={() => run(() => databaseBackupApi.verify(job.id))}>Verify archive</button><button className="underline min-h-12 px-3" disabled={busy || active} onClick={() => run(() => databaseBackupApi.pin(job.id, !job.pinned))}>{job.pinned ? 'Unprotect' : 'Protect'} archive</button><button className="underline min-h-12 px-3 text-red-700" disabled={busy || job.pinned || active} onClick={() => { if (window.confirm('Delete this local archive? The latest validated or protected archive cannot be removed.')) run(() => databaseBackupApi.remove(job.id)); }}>Delete local archive</button></div>}</li>)}</ol>}
    {canRecover && <div className="border rounded p-3 space-y-3"><h3 className="font-semibold">Recovery preparation</h3><p>Live database overwrite is disabled. Select a stored archive for administrator-guided isolated recovery. Encryption keys must be available separately. Run Verify archive successfully within one hour before preparing recovery.</p><label className="block">Recovery archive<select className={field} value={selected} disabled={busy || active} onChange={e => { setSelected(e.target.value); setConfirmed(false); }}><option value="">Select an archive</option>{archives.map(job => <option key={job.id} value={job.id}>{job.kind} · {date(job.createdAt)}</option>)}</select></label><p>Archive checksum: {selectedArchive ? selectedArchive.sha256 ?? 'Unavailable. Verify archive.' : 'Select an archive'} · Last verified: {date(selectedArchive?.verifiedAt)}</p><label className="flex gap-3 items-center min-h-12"><input type="checkbox" checked={confirmed} disabled={busy || !selectedArchive} onChange={e => setConfirmed(e.target.checked)} />I authorize recovery preparation and understand that an isolated restore drill is required.</label><button className={button} disabled={busy || active || !selectedArchive || !confirmed || !recoveryVerified} onClick={() => run(async () => { const result = await databaseBackupApi.recovery(selected, confirmed); setNotice(result.message); })}>Prepare guided recovery</button><p className="text-sm">This protects the archive from retention. Follow docs/RECOVERY_DRILL.md. This action does not change live business data.</p></div>}
  </section>;
}
