import { useState } from 'react';
import { Link } from 'react-router-dom';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import apiClient from '../api/apiClient';
import { PageHeader } from '../components/ui';
import { SafeImage } from '../components/SafeImage';
import { useAuthStore } from '../stores/authStore';
import { hasPermission } from '../auth/hasPermission';
import { purchaseErrorMessage } from '../lib/purchaseValidation';
import { formatMoney } from '../lib/formatMoney';
import { HistoricalPreviewPanel } from '../components/HistoricalPreviewPanel';
import { AccountSecurity } from '../components/AccountSecurity';
import { AiProviderSettings } from '../components/AiProviderSettings';
type Profile = { name: string; brandingTitle?: string; brandingLogoUrl?: string; gstNumber?: string; address?: string; phone?: string; contactEmail?: string; version: string; hasUploadedLogo: boolean; logoUploadAvailable: boolean };
type Preferences = { notificationsEnabled: boolean; notificationKinds: string[] };
type Personal = { id: string; name: string; email: string };
type Credential = { credentialType: string; configured: boolean; lastFour: string; updatedAt?: string; version: string };
const kinds = { low_stock: 'Low stock alerts', delivery: 'Delivery updates', stock_variance: 'Stock variance', staff_alert: 'Staff requests & reorder', opening_stock: 'Opening stock reminders', physical_reminder: 'Physical stock reminders' };
const credentials = { openrouter_key: 'OpenRouter API key', gemini_key: 'Gemini API key', groq_key: 'Groq API key', openai_key: 'OpenAI API key', whatsapp_api_key: 'WhatsApp Cloud API token', whatsapp_staff_number: 'Staff WhatsApp number', whatsapp_phone_number_id: 'WhatsApp phone number ID' };
const field = 'block w-full min-w-0 border rounded p-3 mt-1 disabled:bg-slate-50';
const button = 'px-4 py-3 rounded bg-emerald-800 text-white disabled:opacity-50';
const section = 'rounded-xl border bg-white p-4 space-y-4 min-w-0';
export default function SettingsPage() {
  const user = useAuthStore(s => s.user); const cache = useQueryClient(); const role = user?.currentBusiness?.role ?? '';
  const owner = ['Owner', 'Admin', 'SuperAdmin'].includes(role), credentialOwner = ['Owner', 'Admin', 'SuperAdmin'].includes(role);
  const [draft, setDraft] = useState<Profile | null>(null), [prefsDraft, setPrefsDraft] = useState<Preferences | null>(null), [personalDraft, setPersonalDraft] = useState<string | null>(null);
  const [notice, setNotice] = useState(''), [uploadError, setUploadError] = useState(''), [credentialType, setCredentialType] = useState('openrouter_key'), [credentialValue, setCredentialValue] = useState('');
  const profile = useQuery({ queryKey: ['settings', 'business'], queryFn: async () => (await apiClient.get<Profile>('/settings/business')).data });
  const preferences = useQuery({ queryKey: ['settings', 'notifications'], queryFn: async () => (await apiClient.get<Preferences>('/settings/notifications')).data });
  const personal = useQuery({ queryKey: ['settings', 'profile'], queryFn: async () => (await apiClient.get<Personal>('/settings/profile')).data });
  const provider = useQuery({ queryKey: ['settings', 'credentials'], enabled: credentialOwner, queryFn: async () => (await apiClient.get<Credential[]>('/settings/credentials')).data });
  const command = useQuery({ queryKey: ['operations', 'owner-dashboard'], enabled: credentialOwner, queryFn: async () => (await apiClient.get<{ lowStockCount: number; outOfStockCount: number; pendingDamageCount: number; aiRequestsToday?: number; backupLastStatus?: string; backupLastAt?: string; backupLastSizeBytes?: number; spendLast7Days?: number; exceptions: string[]; staffPerformance: { staffId: string; staffName: string; pending: number; completed: number; rejected: number }[] }>('/operations/owner-dashboard')).data });
  const update = useMutation({ mutationFn: async (d: Profile) => (await apiClient.put<Profile>('/settings/business', d)).data, onSuccess: d => { cache.setQueryData(['settings', 'business'], d); setDraft(null); setNotice('Business profile saved.'); } });
  const prefs = useMutation({ mutationFn: async (d: Preferences) => (await apiClient.put<Preferences>('/settings/notifications', d)).data, onSuccess: d => { cache.setQueryData(['settings', 'notifications'], d); setPrefsDraft(null); setNotice('Notification preferences saved.'); } });
  const account = useMutation({ mutationFn: async (name: string) => (await apiClient.put<Personal>('/settings/profile', { name })).data, onSuccess: d => { cache.setQueryData(['settings', 'profile'], d); setPersonalDraft(null); useAuthStore.setState(s => ({ user: s.user ? { ...s.user, name: d.name } : null })); setNotice('Personal profile saved.'); } });
  const credential = useMutation({ mutationFn: async () => (await apiClient.put<Credential>('/settings/credentials/' + credentialType, { value: credentialValue.trim(), expectedVersion: provider.data?.find(c => c.credentialType === credentialType)?.version })).data, onSuccess: d => { cache.setQueryData<Credential[]>(['settings', 'credentials'], old => [...(old ?? []).filter(c => c.credentialType !== d.credentialType), d]); setCredentialValue(''); setNotice('Provider credential saved.'); } });
  const imageMutation = useMutation({ mutationFn: async (file: File | null) => {
    if (file) { if (file.size > 2 * 1024 * 1024 || !['image/png', 'image/jpeg', 'image/webp'].includes(file.type)) throw new Error('Use JPEG, PNG or WebP up to 2 MB.'); const data = new FormData(); data.append('file', file); data.append('version', profile.data!.version); return (await apiClient.post<Profile>('/settings/business/logo', data, { headers: { 'Content-Type': 'multipart/form-data' } })).data; }
    return (await apiClient.delete<Profile>('/settings/business/logo', { params: { version: profile.data!.version } })).data;
  }, onSuccess: d => { cache.setQueryData(['settings', 'business'], d); setNotice('Business logo updated.'); }, onError: e => setUploadError(purchaseErrorMessage(e)) });
  const refresh = useMutation({ mutationFn: async () => { await Promise.all(['dashboard', 'reports', 'catalog', 'suppliers', 'brokers', 'purchases', 'operations'].map(key => cache.invalidateQueries({ queryKey: [key] }))); }, onSuccess: () => setNotice('Workspace refreshed.') });
  const values = draft ?? profile.data, prefValues = prefsDraft ?? preferences.data;
  const failure = profile.error || preferences.error || personal.error || provider.error || command.error || update.error || prefs.error || account.error || credential.error || refresh.error;
  const busy = update.isPending || prefs.isPending || account.isPending || credential.isPending || imageMutation.isPending;
  const cancel = (discard: () => void) => { if (window.confirm('Discard unsaved changes?')) discard(); };
  const resetErrors = () => { update.reset(); prefs.reset(); account.reset(); credential.reset(); refresh.reset(); setUploadError(''); void cache.invalidateQueries({ queryKey: ['settings'] }); void cache.invalidateQueries({ queryKey: ['operations', 'owner-dashboard'] }); };
  return <div className="space-y-6 min-w-0"><PageHeader title="Settings" subtitle="Business profile, notifications and workspace shortcuts." />
    {notice && <p role="status" className="text-emerald-800">{notice}</p>}{failure && <p role="alert" className="text-red-700">{purchaseErrorMessage(failure)} <button className="underline min-h-12 px-3" onClick={resetErrors}>Retry</button></p>}
    <section className={section}><h2 className="text-lg font-semibold">Personal profile</h2>{personal.isLoading && <p role="status">Loading account…</p>}{personal.data && <form onSubmit={e => { e.preventDefault(); setNotice(''); account.mutate(personalDraft ?? personal.data!.name); }}><fieldset disabled={busy} className="space-y-3">
      <p className="break-words">{personal.data.email} · {role}</p><label className="block">Your name<input className={field} required maxLength={150} value={personalDraft ?? personal.data.name} onChange={e => setPersonalDraft(e.target.value)} /></label><div className="flex flex-wrap gap-3"><button className={button} disabled={personalDraft === null}>Save personal profile</button><button className="p-3" type="button" disabled={personalDraft === null} onClick={() => cancel(() => setPersonalDraft(null))}>Cancel personal edits</button></div>
    </fieldset></form>}</section>
    <section className={section}><h2 className="text-lg font-semibold">Business profile</h2>{!owner && <p>Only the business owner can change this profile.</p>}{profile.isLoading && <p role="status">Loading profile…</p>}{values && <><SafeImage key={values.version} src={values.hasUploadedLogo ? '/settings/business/logo' : values.brandingLogoUrl} authenticated={values.hasUploadedLogo} alt="Business logo" />
      <form onSubmit={e => { e.preventDefault(); setNotice(''); update.mutate(values); }}><fieldset disabled={!owner || busy} className="grid sm:grid-cols-2 gap-4">{(['name', 'brandingTitle', 'gstNumber', 'address', 'phone', 'contactEmail', 'brandingLogoUrl'] as const).map(key => <label className="block min-w-0 text-sm" key={key}>{{ name: 'Business name', brandingTitle: 'Display title', gstNumber: 'GST number', address: 'Address', phone: 'Phone', contactEmail: 'Contact email', brandingLogoUrl: 'Logo URL (HTTPS)' }[key]}<input className={field} required={key === 'name'} maxLength={{ name: 255, brandingTitle: 128, gstNumber: 20, address: 2000, phone: 32, contactEmail: 255, brandingLogoUrl: 512 }[key]} type={key === 'contactEmail' ? 'email' : key === 'brandingLogoUrl' ? 'url' : 'text'} value={values[key] ?? ''} onChange={e => setDraft({ ...values, [key]: e.target.value || undefined })} /></label>)}{owner && <div className="flex flex-wrap gap-3 sm:col-span-2"><button disabled={!draft} className={button}>Save profile</button><button type="button" className="p-3" disabled={!draft} onClick={() => cancel(() => setDraft(null))}>Cancel business edits</button></div>}</fieldset></form>
      {owner && <div className="space-y-3">{profile.data?.logoUploadAvailable ? <label className="block">Upload logo (JPEG, PNG, WebP · up to 2 MB)<input aria-label="Upload business logo" className="block w-full text-sm mt-2" type="file" accept="image/png,image/jpeg,image/webp" disabled={busy || !!draft} onChange={e => { setUploadError(''); if (e.target.files?.[0]) imageMutation.mutate(e.target.files[0]); e.target.value = ''; }} /></label> : <p>Logo upload is unavailable until storage is configured. You can set an HTTPS logo URL.</p>}{draft && <p>Save or cancel profile edits before changing the logo.</p>}{(values.hasUploadedLogo || values.brandingLogoUrl) && <button className="underline min-h-12" disabled={busy || !!draft} onClick={() => { if (window.confirm('Remove the business logo?')) imageMutation.mutate(null); }}>Remove logo</button>}{uploadError && <p role="alert" className="text-red-700">{uploadError}</p>}</div>}
    </>}</section>
    <section className={section}><h2 className="text-lg font-semibold">Notifications</h2>{preferences.isLoading && <p role="status">Loading preferences…</p>}{prefValues && <form onSubmit={e => { e.preventDefault(); setNotice(''); prefs.mutate(prefValues); }}><fieldset disabled={busy} className="space-y-3">
      <label className="flex gap-3 items-center min-h-12"><input type="checkbox" checked={prefValues.notificationsEnabled} onChange={e => setPrefsDraft({ ...prefValues, notificationsEnabled: e.target.checked })} />Enable notifications</label>{Object.entries(kinds).map(([key, label]) => <label key={key} className="flex gap-3 items-center min-h-12"><input type="checkbox" disabled={!prefValues.notificationsEnabled} checked={prefValues.notificationKinds.includes(key)} onChange={e => setPrefsDraft({ ...prefValues, notificationKinds: e.target.checked ? [...prefValues.notificationKinds, key] : prefValues.notificationKinds.filter(k => k !== key) })} />{label}</label>)}
      <div className="flex flex-wrap gap-3"><button className={button} disabled={!prefsDraft}>Save notifications</button><button className="p-3" type="button" disabled={!prefsDraft} onClick={() => cancel(() => setPrefsDraft(null))}>Cancel notification edits</button></div>
    </fieldset></form>}</section>
    {credentialOwner && <section className={section}><h2 className="text-lg font-semibold">API credentials</h2><p>Saved values are encrypted and never shown again. AI providers use the saved business key before the server fallback.</p>{provider.isLoading && <p role="status">Loading credentials…</p>}{provider.data && <><ul className="space-y-2">{Object.entries(credentials).map(([type, label]) => { const saved = provider.data.find(c => c.credentialType === type); return <li key={type} className="break-words">{label}: {saved ? 'Configured · •••• ' + saved.lastFour : 'Not configured'}{saved?.updatedAt && ' · Updated ' + saved.updatedAt.slice(0, 10)}</li>; })}</ul>
      <form onSubmit={e => { e.preventDefault(); setNotice(''); credential.mutate(); }}><fieldset disabled={busy} className="space-y-3"><label className="block">Credential type<select className={field} value={credentialType} onChange={e => { if (!credentialValue || window.confirm('Discard the entered credential?')) { setCredentialValue(''); setCredentialType(e.target.value); } }}>{Object.entries(credentials).map(([type, label]) => <option key={type} value={type}>{label}</option>)}</select></label><label className="block">New credential value<input className={field} type="password" autoComplete="new-password" required maxLength={4096} value={credentialValue} onChange={e => setCredentialValue(e.target.value)} /></label><div className="flex flex-wrap gap-3"><button className={button} disabled={!credentialValue.trim()}>Save credential</button><button className="p-3" type="button" disabled={!credentialValue} onClick={() => cancel(() => setCredentialValue(''))}>Cancel credential edits</button></div></fieldset></form>
    </>}</section>}
    {credentialOwner && <section className={section}><h2 className="text-lg font-semibold">Owner command center</h2>{command.isLoading && <p role="status">Loading business overview…</p>}{command.data && <><div className="grid sm:grid-cols-3 gap-3"><p>Low stock: {command.data.lowStockCount}</p><p>Out of stock: {command.data.outOfStockCount}</p><p>Damage awaiting review: {command.data.pendingDamageCount}</p></div>{owner && command.data.spendLast7Days !== undefined && <p>Purchase spend · last 7 days: {formatMoney(command.data.spendLast7Days)}</p>}<h3 className="font-semibold">Integration telemetry</h3><p>AI requests today (UTC): {command.data.aiRequestsToday ?? "Unavailable"}</p><p>Latest server backup: {command.data.backupLastStatus ?? "No run recorded"}{command.data.backupLastAt && " · " + new Date(command.data.backupLastAt).toLocaleString()}{command.data.backupLastSizeBytes != null && " · " + command.data.backupLastSizeBytes.toLocaleString() + " bytes"}</p><p>Owners can review WhatsApp delivery status on each confirmed purchase. Sending requires configured credentials and server enablement.</p><h3 className="font-semibold">Exceptions</h3>{command.data.exceptions.length ? <ul className="list-disc pl-5">{command.data.exceptions.map(e => <li key={e}>{e}</li>)}</ul> : <p>No stock, damage or task exceptions.</p>}<h3 className="font-semibold">Staff performance</h3>{command.data.staffPerformance.length ? command.data.staffPerformance.map(p => <p key={p.staffId}>{p.staffName}: {p.completed} completed · {p.pending} pending · {p.rejected} rejected</p>) : <p>No assignment history yet.</p>}</>}</section>}

    <section className={section}><h2 className="text-lg font-semibold">Workspace</h2><div className="flex flex-wrap gap-4"><Link to="/settings/help" className="underline min-h-12">How to use this app</Link>{["Owner", "Admin", "Manager", "SuperAdmin"].includes(role) && hasPermission(user, "reports.view") && <Link to="/settings/backup" className="underline min-h-12">Export &amp; Backup</Link>}</div><div className="flex flex-wrap gap-4">{hasPermission(user, 'purchase.create') && <Link to="/purchases/new" className="underline min-h-12">New purchase</Link>}{hasPermission(user, 'users.view') && <Link to="/users" className="underline min-h-12">Users</Link>}{role !== "Staff" && hasPermission(user, "purchase.view") && <Link to="/purchases/list" className="underline min-h-12">Purchases</Link>}<Link to="/operations" className="underline min-h-12">Daily operations</Link>{hasPermission(user, 'reports.view') && <Link to="/reports" className="underline min-h-12">Reports</Link>}{owner && <Link to="/dashboard" className="underline min-h-12">Dashboard</Link>}</div><button className={button} disabled={refresh.isPending} onClick={() => refresh.mutate()}>Refresh all stats</button></section>
    <AccountSecurity />
    {credentialOwner && <AiProviderSettings />}
    {owner && <Link to="/audit" className="block underline min-h-12">Audit history and staff activity</Link>}
    <HistoricalPreviewPanel key={user?.id + ':' + user?.currentBusiness?.businessId + ':' + role} />
  </div>;
}
